# Master Databases from Scratch in Hours

Background:
This tutorial is designed for fast-paced learners who want to bridge the gap between theoretical database concepts and real-world application. By mapping data structures to our daily lives in Winnipeg, we aim to master the essentials of database management through hands-on practice rather than rote memorization.

*Even so, it is still highly recommended that you prioritize reading and studying the official manual once you can understand the official PostgreSQL tutorial.*


Key Principles:

Why PostgreSQL? We recommend using PostgreSQL. In the era of AI and advanced data science, PostgreSQL offers a more robust and future-proof ecosystem compared to MySQL (MariaDB).

Practice Over Theory: Skill acquisition is driven by application. By repeatedly applying SQL syntax to solve actual business problems and logistics, you will internalize these skills much faster.

Our Case Study: The PACE Skating League To make this journey intuitive, we will build our database around the story of a group of PACE students exploring Winnipeg’s ice rinks. Imagine we are tasked with managing our skating sessions using PostgreSQL. We will create a system to coordinate member profiles, cost control (gas and fees), location and date planning, and the skill progression of each skater.

## 1. Pre-Course Setup

1. Download and Install PyCharm Get the professional IDE here: https://www.jetbrains.com/pycharm/

2. Apply for the One-Year Free Student Pack Since you are a student, you can unlock all professional features for free: https://www.jetbrains.com/academy/student-pack/
Just use pace webmail(xxx@webmail.uwinnipeg.com)

3. Open the Project Drag and drop this file (database-from-beginner-to-master.ipynb) directly into PyCharm to get started.

4. Configure the Data Source Navigate to the right-hand panel of the application to set up your database connection.
![db-conf-2](https://i.ibb.co/xtXDdpv2/image1111.png)
![db-conf-1](https://i.ibb.co/93qDRPg2/image2222.png)
Replace the PostgreSQL database connection and password as shown in Figure

## 2. Let's Begin Our Project.

Please keep in mind that our ultimate goal is to build a formal, complex system—a website used to manage our skating club's members, registrations, costs, courses, and learning progress (even though this is a simulated project).

To implement a website like this, the very first thing we need is **Database (DB) Design**. Only after the DB is ready do we move on to the "Application Layer" things. For example:
* Writing Python backend code to connect with the DB;
* Designing **RESTful HTTP APIs**;
* And finally, developing the **Web HTML pages** (the frontend).

While those parts are exciting, they are not the focus of this lesson. Our mission today starts at the foundation: the Database.


In a professional development lifecycle, before we write a single line of Python code for the application layer, design RESTful APIs, or build HTML frontends, we must first establish the Database Design.

And the very first step of database design is drawing the ER Diagram.

An ER Diagram (Entity-Relationship Diagram) is a visual blueprint that defines the data structure and the logical relationships between different business objects (entities). It acts as the "architectural map" for our data before we build the actual database.


| Entity Name | Database Table | Purpose | Real-world Examples |
| :--- | :--- | :--- | :--- |
| **Club Members** | `club_member` | Manages the identity and profile of everyone in the group. | Jack Ma, Elon Musk, Cesar |
| **Rinks** | `rinks_place` | Manages the directory of skating locations and their features. | Duck Pond, The Forks, St. Vital Park |
| **Skating Logs** | `member_rink_log` | Records the "transactions" of each session (costs, duration, performance). | *Jack Ma \| $40 \| 1.5h \| Level 4* |
| **Skill Tree** | `skill_tree` | A library of industry-standard skating techniques. | Duck walk, Basic stroke, Lateral push |
| **Skill Levels** | `skill_level` | Defines the mastery tiers and groups skills accordingly. | Level 1 (Beginner), Level 2 (Intermediate) |

---

Below is the ER diagram.
![ERD](https://s3.engcard.dpdns.org/images/image333.png)

### Understanding Database Relationships (1:1 and 1:N)
In our PACE Skaters Hub, relationships define how our tables "talk" to each other. We use two main types:

1. One-to-One (1:1)
Definition: Each record in Table A relates to exactly one record in Table B, and vice versa.

The Example: Member ↔ Student ID Card

The Logic: One member can have only one official student ID card, and that specific ID card belongs to only one person.

In the Diagram: You usually use this when splitting a table into two for security or organization (e.g., keeping sensitive home addresses in a separate table).

2. One-to-Many (1:N)
Definition: A single record in Table A (the "Parent") can relate to multiple records in Table B (the "Children"), but each "Child" has only one "Parent."

The Example: Club Member ↔ Skating Logs

The Logic: * One Parent: One member (e.g., Cesar) can go skating many times.

Many Children: Each session recorded in the member_rink_log belongs to only one specific person.

The Example: Rinks ↔ Skating Logs

One rink (e.g., The Forks) can host hundreds of skating sessions. However, one specific session happens at only one rink at a time.

### Understanding the role of db in web service

![flow of web service](https://i.ytimg.com/vi/YGxrvHGCJ2Y/maxresdefault.jpg)

### When SQLs are used?
- Register:  insert a record to `club_member` table.
- Login: select a record from `club_member` and verify their password
- Profile: select member's union information:
    - private sensitive info:  real-name, sin, driver lsn number, birthday, bank account
    - account_info: nick name, login_account, password, salt,
    - club_info: skill_level, activity_count
    - social_media_info: link to facebook, youtube, google.

![login](https://img.freepik.com/free-vector/task-management-app-template_23-2148663598.jpg?semt=ais_user_personalization&w=740&q=80)

- Check-in:  report to our sever that you attend an activity at the Forks or somewhere.
- SQL: insert into member_rink_log
    - Position: APP get you position and server calculate that your reported location is at the Forks with 1km. Server transfer an precise location to a specified rink spot and get its `rinks_place` id and store it.
    - You may need to fill out your expense, commute-distance etc.
    - Sever will auto-fill other fields, activity_date, etc.

![check-in](https://www.innroad.com/wp-content/uploads/2024/03/pz-screen-checkin-953x1024.png)

- Visualization
    - Statistics on member attendance： join query
    - Average monthly expenditure：Aggregate Functions

![visualization](https://bs-uploads.toptal.io/blackfish-uploads/public-files/Untitled-02f60b34f9e95cb821b2fe00a616e55b.png)

## 3. Deep Dive into Tables

When the term "Database Table" feels overwhelming, don't overthink it—just think of it as an **Excel spreadsheet**.


#### Example: The `club_member` Table

| id | name | age | enroll_data | skill_level |
| :--- | :--- |:----|:------------| :--- |
| 1 | Jack Ma | 65  | 2012-01-02  | 4 |
| 2 | Elon Musk | 56  | 2009-09-09  | 9 |
| 3 | Cesar | 28  | 2019-09-09  | 10 |

---

#### DDL vs. DML: The Developer's Vocabulary

Now, we need to create these five tables in PostgreSQL. In the world of databases, we categorize our actions into two main "fancy" terms:

1.  **DDL (Data Definition Language)**: This refers to **creating** or **modifying** the table structure (e.g., creating a table or adding a new column).
2.  **DML (Data Manipulation Language)**: This refers to handling the actual data inside the tables: **C**reate (Insert), **R**ead (Select), **U**pdate, and **D**elete—commonly known as **CRUD**.

> **A Reality Check:** You’ll often hear senior developers joke that even after 10 years, their daily job is still mostly "CRUD." Don't feel discouraged! It's perfectly normal because managing data correctly is the most critical part of any system.

---

### Your Turn: Give it a Try.

You'd better execute the following sql in your own database.

In [ ]:
%%sql
-- 1. Create a member table (Parent Table)
CREATE TABLE club_member (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
phone_number VARCHAR(20),
email_address VARCHAR(100) UNIQUE,
age INT CHECK (age >= 0),
enroll_date DATE DEFAULT CURRENT_DATE
);

-- 2. Create ice rink table (Parent Table)
CREATE TABLE rinks_place (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
address varchar(2048),
postal_code VARCHAR(10),
rental_valid BOOLEAN DEFAULT TRUE
);

CREATE TABLE skills (
id SERIAL PRIMARY KEY,
skill_name VARCHAR(100) NOT NULL -- like Duck Walk
);

CREATE TABLE skill_level (
id SERIAL PRIMARY KEY,
skill_id INT REFERENCES skills(id), -- 1:N relationship
level_number INT UNIQUE NOT NULL, -- such as 1, 2, 3
level_name VARCHAR(50) -- such as Beginner, Intermediate
);

-- 5. Create a skating record sheet (The "Heart" - Child of Member, Rink, and Level)
CREATE TABLE member_rink_log (
id SERIAL PRIMARY KEY,
member_id INT REFERENCES club_member(id) ON DELETE CASCADE,
position INT REFERENCES rinks_place(id),
level_id INT REFERENCES skill_level(id),
activity_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
commute_time INTERVAL, -- PG-specific time interval type, records how long the slide lasted
expense NUMERIC(10, 2) -- Records fuel costs or entrance fees, more accurate than Float

);

In [ ]:
%%sql
-- Insert basic skills (Parent: skills)
INSERT INTO skills (skill_name) VALUES
('Duck Walk'), -- id = 1
('Basic Stroke'),-- id = 2
('Snowplow Stop'), -- id = 3
('Crossovers'); -- id = 4

-- Insert Rink Palces (Parent: rinks_place)
INSERT INTO rinks_place (name, address, postal_code) VALUES
('The Forks', '1 Forks Market Rd, Winnipeg', 'R3C 4L9'),
('Duck Pond', 'Assiniboine Park, Winnipeg', 'R3P 2N6'),
('St. Vital Park', '190 River Rd, Winnipeg', 'R2M 5A4');

-- Insert Club Member  (Parent: club_member)
INSERT INTO club_member (name, phone_number, email_address, age) VALUES
('Cesar', '204-123-4567', 'cesar@winnipeg.ca', 35), -- id=1
('Jack Ma', '204-888-9999', 'jack@alibaba.com', 50),
('Elon Musk', '204-000-1111', 'elon@spacex.com', 52),
('Zack', '204-000-3333', 'zack@winnipeg.ca', 32), -- id=4
('Jimmy', '204-000-6666', 'jim@winnipeg.ca', 33), -- id=5
('Ben', '204-000-2222', 'ben@winnipeg.ca', 29), -- id=6
('Chay', '204-000-8888', 'chay@winnipeg.ca', 23); -- id=7

In [ ]:
%%sql
-- Insert Level
-- Note: Here we assume id 1 is Duck Walk and id 2 is Basic Stroke.
INSERT INTO skill_level (skill_id, level_number, level_name) VALUES
(1, 1, 'Beginner'),      -- Level 1 Related skills Duck Walk
(2, 2, 'Intermediate'),  -- Level 2 Related skills Basic Stroke
(4, 3, 'Advanced');      -- Level 3 Related skills Crossovers

-- Insert the final skating record. (Child of multiple parents)
-- 记录格式：Member(Cesar) at Rink(The Forks) achieving Level(Intermediate)
INSERT INTO member_rink_log (member_id, position, level_id, commute_time, expense,activity_date) VALUES
(1, 1, 3, '1 hour 30 minutes', 20.00,  '2026-02-07 13:05:00'), -- cesar, the forks, advanced, 1.5h
(4, 1, 2, '30 minutes', 20.00,  '2026-02-07 13:00:00'), -- zack, the forks, intermediate,
(6, 1, 2, '50 minutes', 20.00,  '2026-02-07 13:30:00'), -- ben, the forks, intermediate,
(5, 1, 1, '45 minutes', 9.9,  '2026-02-07 12:40:00'),-- jimmy, the forks, beginner, 45m
(7, 1, 2, '40 minutes', 5,  '2026-02-01 12:00:00'); -- chay,

Before proceeding to the next chapter, make sure all the above DDL and DML statements are executed successfully, and get into the habit of checking one of your tables.
select * from club_member;
select * from member_rink_log;

If you use the URL and password provided above, do not execute the SQL in this section.

## 4 Conquering SQL
Now that we have a use case for SQL, learn it with questions in mind, use and practice it. Just one try will allow you to deeply understand and master this skill.

Now, I will present you with about a dozen requirements. You need to write the corresponding SQL statements in your SQL management tool, just like completing an assignment, and check the results for correctness.

#### Using PyCharm to execute SQL statements and manipulate your database
![dbsql](https://i.ibb.co/ks8j4KY2/image555.png)

### 4.1 Query Example

Now we need to see how many registered members there are in our database.

Question Example：Query all member id, name, age, phone number (cellphone) in club_member table.

Example SQL:

In [4]:
%%sql
select id, name, age, phone_number as cellphone from club_member;

   id       name  age     cellphone
0   1      Cesar   35  204-123-4567
1   2    Jack Ma   50  204-888-9999
2   3  Elon Musk   52  204-000-1111
3   4       Zack   32  204-000-3333
4   5      Jimmy   33  204-000-6666
5   6        Ben   29  204-000-2222

### 4.2 Basic SQL Skill

#### Question 1: insert a record
On the afternoon of February 8, 2026, Jimmy secretly went to the duck pond to practice skating for an hour, and our system needs to record this data accurately.

type: DML， Insert
target table: member_rink_log

data-details:
- member: jimmy
- position: The Forks
- activity_date: '2026-02-08'
- level_id: he is at the beginning level, but you have to query the respective level_id in skill_level table.
- commute_time: '10 minutes'
- expense: 0

TIPS:
- You need to query club_member table to query Jimmy's ID, because we just store member_id in table member_rink_log;
- the same as position and level_id

In [7]:
%%sql
select id from club_member where name='Jimmy';

   id
0   5

In [9]:
%%sql
select id from rinks_place where name = 'The Forks';

   id
0   1

In [10]:
%%sql
select id from skill_level where level_name='Beginner';

   id
0   1

In [ ]:
%%sql

Extension Question-1.1:
- Update field `activity_date` of latest inserted record to precise time '2026-02-08 14:00:00'

In [ ]:
%%sql

Extension Question-1.2:
- Delete latest inserted record

In [ ]:
%%sql

#### Question 2: show distinct name

member_rink_log, this table is very important, because it records the data generated by everyone during each training session.

Now we want to know who in our club has actively participated in activities after registering.

Requirement:
- type: DML, SELECT
- use distinct
- table: member_rink_log
- query field: member_id

In [6]:
%%sql

   member_id
0          5
1          4
2          6
3          7
4          1

Expectation: As far as we can see, JackMa(Id=2) and ElonMusk(Id=3) never attend our activity.

#### Question 3: Join

In Question 2, we know that 5 friends participated in our organized ice skating activity, but from the `member_rink_log` table, we can only retrieve the `member_id` of these 5 people.

The `member_id` field in the `member_rink_log` table is the same as the `Id` field in the `club_member` table.

Now we want to make the results from Question 2 display the names of these 5 people more clearly. We need to perform a join query, taking the list obtained from the Question 2 result as a new table, and joining it with `club_member` to form a new combined table. Only then can we display the names of the target members.

Requirement：
- type: DML, SELECT, JOIN
- query field: distinct club_member.name as name

TIPS:
- If you have no idea what to do, you should check the official manual for information on Join.

In [11]:
%%sql

    name
0   Zack
1    Ben
2   Chay
3  Jimmy
4  Cesar

#### Question 4: Order By

Write SQL statements to fulfill the following requirements

Let's see who arrived earliest and who arrived latest on February 7th.

Requirement：
- Returning the list of member_ids and Activity_dates, sorted in descending order by the Activity_date field, will allow us to see the order in which we entered the forks.
- Type： DML, SELECT
- Condition: `activity_date` is between '2026-02-07 00:00:00' and '2026-02-08 00:00:00', which means it's February 7, 2026.

Tip:
- We don't want the records which are not on 2026-02-07

In [13]:
%%sql

   member_id           activity_date
0          5  2026-02-07 12:40:00+00
1          4  2026-02-07 13:00:00+00
2          1  2026-02-07 13:05:00+00
3          6  2026-02-07 13:30:00+00

Extension-4.1:

- For the result of Question 4, return the member name and activity_date instead of the member_id.
- use join with club_member

TIPS:
- LEFT JOIN keeps all hit results from the "Left" table and only attaches matching data from the "Right" table.

- RIGHT JOIN keeps all hit results from the "Right" table and only attaches matching data from the "Left."

- The Golden Rule: If there is no match for a hit result, the "empty" side will simply show up as NULL.

In [14]:
%%sql

    name           activity_date
0  Jimmy  2026-02-07 12:40:00+00
1   Zack  2026-02-07 13:00:00+00
2  Cesar  2026-02-07 13:05:00+00
3    Ben  2026-02-07 13:30:00+00

*If you can write this SQL, you are almost a master of PostgreSQL.*

#### Question 5: Aggregate Functions

Now we want to know how many of us participated on February 7, 2026, how much it cost in total, and what the average cost was.

Requirement:
- type: DML, SELECT
- table: member_rink_log
- query field: count(*), AVG(expense), SUM(expense)
- Condition: `activity_date` is between '2026-02-07 00:00:00' and '2026-02-08 00:00:00', which means it's February 7, 2026.

In [16]:
%%sql

   count     avg   sum
0      4  17.475  69.9

### Question 6: Group By

We measure participants' skating skills using three skill levels. Now we want to know how many people are at the Beginner level, how many are at the Intermediate level, and how many are at the Advanced level.


Requirement：
- type: DML, SELECT
- table: member_rink_log
- Query Fields: level_id, member_count

TIPS：
- group by

In [17]:
%%sql

   level_id  member_count
0         3             1
1         2             3
2         1             1

Extension-6.1:
- For the result of Question 4, return the `level_name` and member_count instead of the level_id.
- use join with skill_level
- Actually, skill_level.id is  member_rink_log.level_id


TIPS:
- You are required to be able to use `order by`, `join`, `Subqueries`
- Learn from Official Manual about **Subqueries** before trying to solve this tricky one.

In [18]:
%%sql

     level_name  member_count
0      Beginner             1
1  Intermediate             3
2      Advanced             1

#### Question 7: Page Query

The Reality of Big Data: Why Pagination Matters
Years later, after participating in hundreds of events, our database has grown from a few rows to tens of thousands of records. In a real industrial environment, it’s common for a single table to exceed millions of rows.

At this scale, running a simple SELECT * FROM member_rink_log is no longer just a query—it’s a performance disaster. Returning millions of rows in one go would:

Choke the Network: The massive Data Payload would slow down the transfer.

Crash the App: The application memory might overflow trying to process all that data.

Kill the UX: No user can (or wants to) scroll through a million rows of data.

This is where Pagination Queries become a mandatory standard in backend engineering.

Requirement:
- In the club_member table, select all adults paginated, with 3 people per page, selecting only the first page.
- type: DML, SELECT
- condition: age greater than 18
- return fields: name, age
- order by: age
- page query: use `limit`, `offset`

In [29]:
%%sql
--  the first page

   name  age
0  Chay   23
1   Ben   29
2  Zack   32

In [31]:
%%sql
-- what about the second page?

      name  age
0    Jimmy   33
1    Cesar   35
2  Jack Ma   50

> The demo show 80% frequently used SQLs in real-word work. But that doesn't mean the practise is enough.
> **It's best to ask questions yourself and then solve it using SQL.**

## Other Advanced Usage

There are some other advanced usages that are also important and need to be mastered, but we'll cover them next time.

1. Constraints & Indexes – The Core of Industrial-Grade Systems

These are crucial for ensuring data integrity.

UNIQUE: Ensures unique email addresses.

CHECK: For example, restricting age from being negative or gas expenses from exceeding $1000.

INDEX: When your logs reach tens of thousands of records, adding an index to `member_id` can reduce query speed from seconds to milliseconds.

2. Transaction Management – The System's "Undo"

This is the most important concept in web backends.

BEGIN / COMMIT / ROLLBACK: